# Generated by Django 5.0.1 on 2024-01-08 04:39

import realestateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[realestateapp.models.email_validate])),
                ('contact', models.CharField(max_length=10, validators=[realestateapp.models.contact_validate])),
                ('password', models.CharField(max_length=15)),
            ],
        ),
    ]
