# Generated by Django 5.0.1 on 2024-01-08 06:32

import realestateapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0002_propertydetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='tenentreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('id_proof', models.FileField(upload_to='idproof/')),
                ('contact', models.CharField(max_length=10, validators=[realestateapp.models.contact_validate])),
            ],
        ),
    ]
