# Generated by Django 5.0.1 on 2024-01-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestateapp', '0003_tenentreg'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenentreg',
            name='password',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
